install.package("tidyverse")
install.package("neonstore")
install.package("tools")
install.package("ncdf4")
install.package("parallel")
install.package("patchwork")
install.package("aws.s3")
install.package("yaml")
install.package("remotes")
install.package("furr")
install.package("broom")
install.package("egg")
install.package("fs")
install.package("zoo")
install.package("tidyr")
install.package("utils")
install.package("ISOweek")
install.package("scoringRules")
install.package("stats")
install.package("tidyselect")
install.package("vctrs")
install.package("zip")
remotes::install_github("rqthomas/cronR")
remotes::install_github("FLARE-forecast/FLAREr", ref = "v2.2.0")
remotes::install_github("FLARE-forecast/GLM3r", ref = "FLARErv1")