restart_file: .na
start_datetime: 2022-01-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-12-31 00:00:00
forecast_horizon: 2.0
sim_name: Simstrat
configure_flare: configure_flare_BARC_Simstrat.yml
use_s3: no