restart_file: .na
start_datetime: 2023-03-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2023-03-19 00:00:00
forecast_horizon: 3.0
sim_name: flareGOTM_noDA
configure_flare: configure_flare_BARC_GOTM.yml
use_s3: no
