restart_file: .na
start_datetime: 2022-09-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-09-06 00:00:00
forecast_horizon: 2.0
sim_name: Simstrat
configure_flare: configure_flare_TOOL_Simstrat.yml
use_s3: no