restart_file: .na
start_datetime: 2022-10-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2023-03-01 00:00:00
forecast_horizon: 30.0
sim_name: flareGLM_noDA
configure_flare: configure_flare_PRLA.yml
use_s3: TRUE

