file_path:
   qaqc_data_directory: .na
   noaa_directory: .na
   inflow_directory: .na
   configuration_directory: CRAM
   execute_directory: .na
   forecast_output_directory: .na
s3:
  drivers:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/drivers/met/gefs-v12
  inflow_drivers:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/drivers/inflow/neon
  targets:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/targets
  forecasts:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/forecasts/netcdf
  forecasts_parquet:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/forecasts/parquet
  warm_start:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/restart
  scores:
    endpoint: amnh1.osn.mghpcc.org
    bucket: bio230121-bucket01/flare/scores/parquet
location:
   site_id: CRAM
   name: Crampton Lake
   latitude: 46.20967   #Degrees North
   longitude: -89.47369  #Degrees West
da_setup:
    da_method: enkf
    par_fit_method: perturb_const
    ensemble_size:  256
    no_negative_states: TRUE
    assimilate_first_step: FALSE
    use_obs_constraint: TRUE
    obs_filename: CRAM-targets-insitu.csv
model_settings:
   ncore: 4
   model: GOTM
   base_GLM_nml: glm3_CRAM.nml
   base_ler_yaml: LakeEnsemblR_CRAM.yaml
   ler_bathymetry_file: LakeEnsemblR_bathymetry_CRAM.csv
   use_ler: TRUE
   modeled_depths: [0.0,0.25,0.50,0.75,
                    1.00,1.25,1.50,1.75,
                    2.00,2.25,2.50,2.75,
                    3.00,3.25,3.50,3.75,
                    4.00,4.25,4.50,4.75,
                    5.00,5.25,5.50,5.75,
                    6.00,6.25,6.50,6.75,
                    7.00,7.25,7.50,7.75,
                    8.00,8.25,8.50,8.75,
                    9.00,9.25,9.50,9.75,
                    10.00,10.25,10.50,10.75,
                    11.00,11.25,11.50,11.75,
                    12.00,12.50,
                    13.00,13.50,
                    14.00,14.50,
                    15.00,15.50,
                    16.00,16.50,
                    17.00,17.50,
                    18.00,18.50,
                    19.00]
   par_config_file: parameter_calibration_config_CRAM.csv
   obs_config_file: observations_config_CRAM.csv
   states_config_file: states_config_CRAM.csv
   depth_model_sd_config_file: depth_model_sd_CRAM.csv
default_init:
   lake_depth: 19.1 #not a modeled state
   temp: [8, 8, 8, 8, 8,
          8, 8, 8, 8, 8,
          8, 8, 8, 8, 8,
          8, 8, 8, 8, 8,
          8, 8, 8, 8, 8,
          7, 7, 7, 6, 6,
          5, 5, 5, 4, 4,
          4, 4, 4, 4, 4]
   temp_depths: [0.00, 0.10, 0.50, 1.00,
                  1.50, 2.00, 2.50,
                  3.00, 3.50, 4.00,
                  4.50, 5.00, 5.50,
                  6.00, 6.50, 7.00,
                  7.50, 8.00, 8.50,
                  9.00, 9.50, 10.0,
                  10.5, 11.0, 11.5,
                  12.0, 12.5, 13.0,
                  13.5, 14.0, 14.5,
                  15.0, 15.5, 16.0,
                  16.5, 17.0, 17.5,
                  18.0, 18.5, 19.0]
   salinity: 0.0
   snow_thickness: 0.0
   white_ice_thickness: 0.0
   blue_ice_thickness: 0.0
inflow:
   include_inflow: FALSE
   use_forecasted_inflow: FALSE
   forecast_inflow_model: NA
   observed_inflow_filename: NA
   inflow_variables: NA
   use_ler_vars: FALSE
met:
   use_forecasted_met: TRUE
   use_observed_met: FALSE
   local_directory: .na
   observed_met_filename: .na
   use_ler_vars: TRUE
   forecast_lag_days: 1
uncertainty:
   observation: TRUE
   process: TRUE
   weather: TRUE
   initial_condition: TRUE
   parameter: TRUE
   met_downscale: TRUE
   inflow_process: TRUE
output_settings:
   diagnostics_names:  [extc]
   evaluate_past: FALSE
   variables_in_scores: [state, parameter]