restart_file: .na
start_datetime: 2024-05-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2024-07-01 00:00:00
forecast_horizon: 30.0
sim_name: Simstrat_noDA
configure_flare: configure_flare_LIRO_Simstrat.yml
use_s3: TRUE