file_path:
   qaqc_data_directory: .na
   noaa_directory: .na
   inflow_directory: .na
   configuration_directory: LIRO
   execute_directory: .na
   forecast_output_directory: .na
s3:
  drivers:
    endpoint: s3.flare-forecast.org
    bucket: drivers/noaa/gefs-v12-reprocess
  inflow_drivers:
    endpoint: s3.flare-forecast.org
    bucket: drivers/inflow/neon/parquet
  targets:
    endpoint: s3.flare-forecast.org
    bucket: targets/neon
  forecasts:
    endpoint: s3.flare-forecast.org
    bucket: forecasts
  forecasts_parquet:
    endpoint: s3.flare-forecast.org
    bucket: forecasts/parquet
  warm_start:
    endpoint: s3.flare-forecast.org
    bucket: restart/neon
  scores:
    endpoint: s3.flare-forecast.org
    bucket: scores/parquet
location:
   site_id: LIRO
   name: Little Rock Lake
   latitude: 45.998269   #Degrees North
   longitude: -89.704767  #Degrees West
da_setup:
    da_method: enkf
    par_fit_method: perturb_const
    ensemble_size:  256
    no_negative_states: TRUE
    assimilate_first_step: FALSE
    use_obs_constraint: TRUE
    obs_filename: LIRO-targets-insitu.csv
model_settings:
   ncore: 4
   model: Simstrat
   base_GLM_nml: glm3_LIRO.nml
   base_ler_yaml: LakeEnsemblR_LIRO.yaml
   ler_bathymetry_file: LakeEnsemblR_bathymetry_LIRO.csv
   use_ler: TRUE
   modeled_depths: [0.00,0.25,0.50,0.75,
                    1.00,1.25,1.50,1.75,
                    2.00,2.25,2.50,2.75,
                    3.00,3.25,3.50,3.75,
                    4.00,4.25,4.50,4.75,
                    5.00,5.25,5.50,5.75,
                    6.00,6.25,6.50,6.75,
                    7.00,7.25,7.50,7.75,
                    8.00,8.25,8.50,8.75,
                    9.00,9.25,9.50,9.75,
                    10.00]
   par_config_file: parameter_calibration_config_LIRO.csv
   obs_config_file: observations_config_LIRO.csv
   states_config_file: states_config_LIRO.csv
   depth_model_sd_config_file: depth_model_sd_LIRO.csv
default_init:
   lake_depth: 10.1  #not a modeled state
   temp: [18,18,18,18,18,18,16,16,10,8,6,5,5]
   temp_depths: [0.0,0.1,0.5,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0]
   salinity: 0.0
   snow_thickness: 0.0
   white_ice_thickness: 0.0
   blue_ice_thickness: 0.0
inflow:
   include_inflow: FALSE
   use_forecasted_inflow: FALSE
   forecast_inflow_model: NA
   observed_inflow_filename: NA
   inflow_variables: NA
   use_ler_vars: FALSE
met:
   use_forecasted_met: TRUE
   use_observed_met: FALSE
   local_directory: .na
   observed_met_filename: .na
   use_ler_vars: TRUE
   forecast_lag_days: 1
uncertainty:
   observation: TRUE
   process: TRUE
   weather: TRUE
   initial_condition: TRUE
   parameter: TRUE
   met_downscale: TRUE
   inflow_process: TRUE
output_settings:
   diagnostics_names:  [extc]
   evaluate_past: FALSE
   variables_in_scores: [state, parameter]
