restart_file: .na
start_datetime: 2022-09-25 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-10-08 00:00:00
forecast_horizon: 10.0
sim_name: GOTM
configure_flare: configure_flare_LIRO_GOTM.yml
use_s3: no