restart_file: .na
start_datetime: 2022-12-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-12-05 00:00:00
forecast_horizon: 2.0
sim_name: GOTM
configure_flare: configure_flare_PRLA_GOTM.yml
use_s3: no