restart_file: /home/rstudio/NEON-forecast-code/forecasts/PRPO-2021-11-04-PRPO_LAKE.nc
start_datetime: 2021-11-03 00:00:00
end_datetime: .na
forecast_start_datetime: 2021-11-04 00:00:00
forecast_horizon: 16.0
sim_name: PRPO_LAKE
forecast_site: PRPO
forecast_output_directory: .na
forecast_configuration_directory: .na
execute_directory: .na
