file_path:
   qaqc_data_directory: inst/example/data_processed/
   noaa_directory: inst/example/forecasted_drivers/
   inflow_directory: inst/example/forecasted_drivers/
   configuration_directory: inst/example/configuration/
   execute_directory: inst/example/flare_tempdir
   forecast_output_directory: inst/example/forecast_output
   run_config: inst/example/configuration/flarer/configure_run.yml
location:
   site_id: LIRO
   name: Little Rock Lake
   latitude: 45.998269   #Degrees North
   longitude: -89.704767  #Degrees West
metadata:
   generate_eml: TRUE
   forecast_project_id: LITTLE_ROCK_LAKE
   abstract: "This is where a longer description of the forest can be added"
   forecast_title: FLARE
   intellectualRights: insert license
   model_description:
      forecast_model_id: https://github.com/rqthomas/flare/commit/d1ddcb07b9d28863890597503fc4aa4a4496de56
      name: General Lake Model
      type: process-based
      repository: https://github.com/AquaticEcoDynamics/GLM/releases/tag/v3.1.0
   me:
      individualName:
         givenName: "Ryan"
         surName: "McClure"
      electronicMailAddress:  "ryan333@vt.edu"
      id: 0000-0001-6370-3852
da_setup:
   da_method: enkf
   par_fit_method: inflate
   ensemble_size:  100
   localization_distance: .na #distance in meters were covariances in the model error are used
   no_negative_states: TRUE
   assimilate_first_step: FALSE
   use_obs_constraint: TRUE
model_settings:
   ncore: 2
   model_name: glm #other is "null"
   base_GLM_nml: glm3_LIRO.nml
   modeled_depths: [0.0,0.1,0.5,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0]
   par_config_file: parameter_calibration_config_LIRO.csv
   obs_config_file: observations_config_LIRO.csv
   states_config_file: states_config_LIRO.csv
   depth_model_sd_config_file: depth_model_sd_LIRO.csv
default_init:
   lake_depth: 10.1  #not a modeled state
   temp: [18,18,18,18,18,18,16,16,10,8,6,5,5]
   temp_depths: [0.0,0.1,0.5,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0]
   salinity: 0.0
   snow_thickness: 0.0
   white_ice_thickness: 0.0
   blue_ice_thickness: 0.0
inflow:
   use_forecasted_inflow: FALSE
   forecast_inflow_model: FLOWS-NOAAGEFS-AR1
met:
   use_forecasted_met: TRUE
   forecast_met_model: NOAAGEFS_1hr
uncertainty:
   observation: TRUE
   process: TRUE
   weather: TRUE
   initial_condition: TRUE
   parameter: TRUE
   met_downscale: TRUE
   inflow_process: TRUE
output_settings:
   diagnostics_names:  [extc_coef]
