restart_file: .na
start_datetime: 2019-06-08 16:00:00 # spinup start time
end_datetime: .na # spinup end time, if not specified, then defaults to when forecasts start
forecast_start_datetime: 2021-05-05 16:00:00 # noon EST
forecast_horizon: 30
sim_name: test_run
forecast_output_directory: .na
forecast_configuration_directory: .na
execute_directory: .na
