restart_file: .na
start_datetime: 2022-12-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2023-01-01 00:00:00
forecast_horizon: 30.0
sim_name: GOTM
configure_flare: configure_flare_BARC.yml
use_s3: no
