restart_file: .na
start_datetime: 2024-09-25 00:00:00
end_datetime: .na
forecast_start_datetime: 2024-10-15 00:00:00
forecast_horizon: 34.0
sim_name: glm_flare_v3
configure_flare: configure_flare_CRAM.yml
use_s3: TRUE

