restart_file: .na
start_datetime: 2023-10-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2024-02-22 00:00:00
forecast_horizon: 34.0
sim_name: glm_flare_v1
configure_flare: configure_flare_PRLA.yml
use_s3: TRUE

