on:
  workflow_dispatch:
  schedule:
  - cron: "0 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rqthomas/flare-rocker:4.2.1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Run automatic prediction file
        run: Rscript $GITHUB_WORKSPACE/R/auto_run_trigger.R
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_PAT: ${{ secrets.PAT }}
      - name: Commit files
        run: |
           git config --global --add safe.directory $GITHUB_WORKSPACE
           git config --local user.name "$GITHUB_ACTOR"
           git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
           git add reruns/*
           git commit -m "adding rerun files" || echo "No changes to commit"
           git push || echo "No changes to commit"
