on:
  workflow_dispatch:
  #schedule:
  #- cron: "0 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rqthomas/flare-rocker:4.2.1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          
# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:  Rscript $GITHUB_WORKSPACE/R/auto_run_trigger.R
      - name: GIT commit and push all changed files
        env: 
          GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          git config user.name OlssonF
          git config user.email freyao@vt.edu
          git remote set-url --push origin https://OlssonF:$GITHUB_TOKEN@github.com/OlssonF/NEON-forecast-code
          git add rerun
          git commit -a -m "files to rerun"
          git push
