on:
  workflow_dispatch:
  #schedule:
  #- cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eco4cast/rocker-neon4cast
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
# Point to the right path, run the right Rscript command
      - name: Run automatic forecast submission file
        run: /usr/local/bin/r $GITHUB_WORKSPACE/workflows/default/challenge_submission.R 
